# Generated by Django 3.2.5 on 2021-07-20 13:47

import demo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleach', models.TextField(max_length=50)),
                ('desc', models.TextField(max_length=200)),
            ],
            options={
                'db_table': 'achievements',
            },
        ),
        migrations.CreateModel(
            name='Educationdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qulification', models.TextField(max_length=191)),
                ('college', models.TextField(max_length=191)),
                ('board', models.TextField(max_length=191)),
                ('year', models.TextField(max_length=191)),
                ('percentageclass', models.TextField(max_length=191)),
            ],
            options={
                'db_table': 'education1',
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.CharField(max_length=100)),
                ('companyname', models.CharField(max_length=100)),
                ('startfrom', models.DateField()),
                ('startto', models.DateField()),
                ('programinglanguage', models.TextField(max_length=200)),
                ('address', models.TextField(max_length=500)),
                ('role', models.TextField(max_length=200)),
            ],
            options={
                'db_table': 'experience',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=191)),
                ('price', models.TextField(max_length=50)),
                ('description', models.TextField(max_length=500, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=demo.models.filepath)),
            ],
            options={
                'db_table': 'demo_item1',
            },
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fristname', models.TextField(max_length=191)),
                ('secondname', models.TextField(max_length=191)),
                ('lastname', models.TextField(max_length=191)),
                ('title', models.TextField(max_length=191)),
                ('email', models.TextField(max_length=191)),
                ('mobile', models.TextField(max_length=15)),
                ('dob', models.TextField(max_length=20)),
                ('gender', models.TextField(max_length=15)),
                ('phone', models.TextField(max_length=15)),
                ('linkedln', models.TextField(max_length=500)),
                ('language', models.TextField(max_length=50)),
                ('R_id', models.IntegerField(max_length=50)),
                ('profilepicture', models.ImageField(blank=True, null=True, upload_to=demo.models.filepath)),
                ('about', models.TextField(max_length=1800)),
                ('address', models.TextField(max_length=750)),
            ],
            options={
                'db_table': 'personal1',
            },
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('mobile', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=150)),
                ('confirmpassword', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'register1',
            },
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=200)),
                ('rating', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'skiles',
            },
        ),
    ]
